name: Keep API Awake

on:
  schedule:
    - cron: "*/14 * * * *"  # a cada 14 minutos

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping API
        run: curl https://olx-back-end.onrender.com/smartphones/listAll
